# this action folder was not continued to work on, so it's just this one action file here
#goal, empty                
---                             
#result, Odometry array             
nav_msgs/Odometry[] result_odom_array                
---                             
#feedback, empty